spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/passkeeper
    username: postgres
    password: 123456
    hikari:
      autoCommit: false
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 1800000
      minimumIdle: 10
      maximumPoolSize: 40

  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug

server:
  port : 8096

security.basic.enabled: false
management.security.enabled: false
